### ISSUE TITLE
接受到tpa没有出现表单

### ISSUE THREAD

**Issue by xiaoluofa** [DongShaoNB/BedrockPlayerSupport#17]
![IMG_2620](https://github.com/DongShaoNB/BedrockPlayerSupport/assets/75927411/dd2315f8-67eb-4d09-8a8f-633e50c53ad8)
经过多次测试，folia1.20.4，huskhome

**Comment by xiaoluofa** [comment]
![image](https://github.com/DongShaoNB/BedrockPlayerSupport/assets/75927411/0c8b61f4-e095-453e-97e9-14ebcdb2e916)
还有吐槽一下这个

**Comment by xiaoluofa** [comment]
基岩版玩家重生后弹出返回死亡点表单
这个也没有正常出现

**Comment by xiaoluofa** [comment]
homegui无法显示home列表，出现了表单，但是为空

**Comment by DongShaoNB** [comment]
请测试 https://github.com/DongShaoNB/BedrockPlayerSupport/actions/runs/8106996093，查看是否能正常使用

**Comment by xiaoluofa** [comment]
> 请测试 https://github.com/DongShaoNB/BedrockPlayerSupport/actions/runs/8106996093 查看是否能正常使用

缺失语言文件插件无法正常加载

**Comment by DongShaoNB** [comment]
> > 请测试 https://github.com/DongShaoNB/BedrockPlayerSupport/actions/runs/8106996093 查看是否能正常使用
> 
> 缺失语言文件插件无法正常加载

https://github.com/DongShaoNB/BedrockPlayerSupport/actions/runs/8115418522 这个 那个弄错了🥲
