### ISSUE TITLE
可設定在死亡返回時使用的指令

### ISSUE THREAD

**Issue by MagicTeaMC** [DongShaoNB/BedrockPlayerSupport#40]
**简述功能**
CMI 預設的死亡返回指令為 /dback，而 /back 並不會返回死亡點，所以需要新增個可設定的選項。

**补充**
無

**Comment by DongShaoNB** [comment]
CMI用/back也可以返回死亡点吧我记得（？）



---原始邮件---
发件人: "Maoyue ***@***.***&gt;
发送时间: 2024年3月31日(周日) 上午10:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [DongShaoNB/BedrockPlayerSupport] 可設定在死亡返回時使用的指令 (Issue #40)




 
简述功能
 CMI 預設的死亡返回指令為 /dback，而 /back 並不會返回死亡點，所以需要新增個可設定的選項。
 
补充
 無

**Comment by MagicTeaMC** [comment]
> CMI用/back也可以返回死亡点吧我记得（？）
> […](#)
> ---原始邮件--- 发件人: "Maoyue ***@***.***&gt; 发送时间: 2024年3月31日(周日) 上午10:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [DongShaoNB/BedrockPlayerSupport] 可設定在死亡返回時使用的指令 (Issue #40) 简述功能 CMI 預設的死亡返回指令為 /dback，而 /back 並不會返回死亡點，所以需要新增個可設定的選項。 补充 無 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我用預設的 config 測試，確定是返回上一個記錄的點（例如上次 /tpa 到的位置）

**Comment by DongShaoNB** [comment]
已添加 https://github.com/DongShaoNB/BedrockPlayerSupport/actions/runs/8500352455
