### ISSUE TITLE
没找到电梯插件的库借用一下这里~

### ISSUE THREAD

**Issue by 404forever1** [DongShaoNB/BedrockPlayerSupport#45]
电梯使用会造成严重的tps滞后
![image](https://github.com/DongShaoNB/BedrockPlayerSupport/assets/168977890/9825977d-5254-4667-81a7-b739b7ec4c0e)

**Comment by DongShaoNB** [comment]
（？）

**Comment by 404forever1** [comment]
草，不好意思，还以为是otto得库，怎么到这里来了

**Comment by DongShaoNB** [comment]
@HaHaWTH 🥵

**Comment by 404forever1** [comment]
> @HaHaWTH 🥵

这多尴尬啊，我发它那边了哈哈哈

**Comment by 404forever1** [comment]
> @HaHaWTH 🥵

刚才看到它fork了这个项目，可能没仔细看点到你这里来了哈哈哈

**Comment by HaHaWTH** [comment]
> > @HaHaWTH 🥵
> 
> 刚才看到它fork了这个项目，可能没仔细看点到你这里来了哈哈哈

Don't use this, just piece of bullshit. I am tired to maintain so many projects tbh, gonna take a break
