### ISSUE TITLE
使用基岩版输入指令却显示『你不是基岩版玩家！ 』

### ISSUE THREAD

**Issue by cgw2023** [DongShaoNB/BedrockPlayerSupport#46]
**简述BUG**
当我使用基岩版登入geyser服务器，输入指令 tpgui 却显示『你不是基岩版玩家！ 』

**复现步骤**
怎么复现这个BUG:
1. 登入服务器
2. 输入指令 /tpgui

**截图**
![Screenshot_20240522_161144_Minecraft](https://github.com/DongShaoNB/BedrockPlayerSupport/assets/136877036/ad61d20c-9cc7-474e-bfe1-9dc85c023e0d)

**环境**
 - 服务端及版本: folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf-ec6b172
 - 插件版本 BedrockPlayerSupport-1.8.3
 - 其他补充 velocity-3.3.0-SNAPSHOT-390

**补充**
连接方法为
velocity geyser -> folia 

 [BedrockPlayerSupport] Enabling BedrockPlayerSupport v1.8.3
 [BedrockPlayerSupport] -----------------
 [BedrockPlayerSupport] 检测支持插件是否启用: 
 [BedrockPlayerSupport] floodgate: true
 [BedrockPlayerSupport] CMI: false
 [BedrockPlayerSupport] EssentialsX: true
 [BedrockPlayerSupport] HuskHomes: false
 [BedrockPlayerSupport] AuthMe: false
 [BedrockPlayerSupport] CatSeedLogin: false
 [BedrockPlayerSupport] NexAuth: false
 [BedrockPlayerSupport] -----------------

velocity 开启java正版验证
geyser velocity搭配floodgate 给基岩连线
folia floodgate 用相同velocity的 key.pem
无任何auth插件在velocity/folia

测试服务器测试中发现问题，基岩连线为直连，无haproxy

**Comment by DongShaoNB** [comment]
看看Velocity上的Geyser配置文件，以下配置项是否正确设置

- `auth-type` 设置为 `floodgate`
- `send-floodgate-data` 设置为 `true`

**Comment by cgw2023** [comment]
正常了，謝謝。
