### ISSUE TITLE
关于AuthMe基岩版登录GUI的一些建议

### ISSUE THREAD

**Issue by HaHaWTH** [DongShaoNB/BedrockPlayerSupport#5]
authme默认在玩家未注册的情况下会拦截所有交互行为，所有事件都要过一遍listenerService，或许可以参考下这个：https://github.com/HaHaWTH/AuthMeReReloaded/blob/master/src/main/java/fr/xephi/authme/listener/ListenerService.java#L87

authme的配置文件中也提供了InventoryWhitelist的配置项，只要知道基岩版gui的窗口名的话或许也可以(? 貌似都需要在authme上动刀子

**Comment by DongShaoNB** [comment]
> authme默认在玩家未注册的情况下会拦截所有交互行为，所有事件都要过一遍listenerService，或许可以参考下这个：https://github.com/HaHaWTH/AuthMeReReloaded/blob/master/src/main/java/fr/xephi/authme/listener/ListenerService.java#L87
> 
> authme的配置文件中也提供了InventoryWhitelist的配置项，只要知道基岩版gui的窗口名的话或许也可以(? 貌似都需要在authme上动刀子

但是基岩版直接跳过登录不是更方便吗🤔

**Comment by HaHaWTH** [comment]
感觉注册也需要一个gui，毕竟注册这东西没法跳过🧐

**Comment by HaHaWTH** [comment]
> > authme默认在玩家未注册的情况下会拦截所有交互行为，所有事件都要过一遍listenerService，或许可以参考下这个：https://github.com/HaHaWTH/AuthMeReReloaded/blob/master/src/main/java/fr/xephi/authme/listener/ListenerService.java#L87
> > authme的配置文件中也提供了InventoryWhitelist的配置项，只要知道基岩版gui的窗口名的话或许也可以(? 貌似都需要在authme上动刀子
> 
> 但是基岩版直接跳过登录不是更方便吗🤔

感觉注册也需要一个gui，毕竟注册这东西没法跳过🧐

跳过登录可能有潜在的绕过问题(未测试)：
如：玩家114 514通过Geyser+floodgate进入服务器，floodgate会自动将空格换为下划线，此时如果有一个114_514的基岩版玩家也进入服务器是否也会自动登录

**Comment by DongShaoNB** [comment]
> 
> 
> 
> 
> > > authme默认在玩家未注册的情况下会拦截所有交互行为，所有事件都要过一遍listenerService，或许可以参考下这个：https://github.com/HaHaWTH/AuthMeReReloaded/blob/master/src/main/java/fr/xephi/authme/listener/ListenerService.java#L87
> > > authme的配置文件中也提供了InventoryWhitelist的配置项，只要知道基岩版gui的窗口名的话或许也可以(? 貌似都需要在authme上动刀子
> > 
> > 但是基岩版直接跳过登录不是更方便吗🤔
> 
> 感觉注册也需要一个gui，毕竟注册这东西没法跳过🧐
> 
> 跳过登录可能有潜在的绕过问题(未测试)：
> 如：玩家114 514通过Geyser+floodgate进入服务器，floodgate会自动将空格换为下划线，此时如果有一个114_514的基岩版玩家也进入服务器是否也会自动登录

注册可以试着弄个GUI。你说的这个情况理论上不会出现，因为这两个玩家的UUID不一样，自动登录了也不会使用一样的数据，这点是可以保证的。但是有可能会因为ID相同被踢出（？）

**Comment by HaHaWTH** [comment]
> > > > authme默认在玩家未注册的情况下会拦截所有交互行为，所有事件都要过一遍listenerService，或许可以参考下这个：https://github.com/HaHaWTH/AuthMeReReloaded/blob/master/src/main/java/fr/xephi/authme/listener/ListenerService.java#L87
> > > > authme的配置文件中也提供了InventoryWhitelist的配置项，只要知道基岩版gui的窗口名的话或许也可以(? 貌似都需要在authme上动刀子
> > > 
> > > 
> > > 但是基岩版直接跳过登录不是更方便吗🤔
> > 
> > 
> > 感觉注册也需要一个gui，毕竟注册这东西没法跳过🧐
> > 跳过登录可能有潜在的绕过问题(未测试)：
> > 如：玩家114 514通过Geyser+floodgate进入服务器，floodgate会自动将空格换为下划线，此时如果有一个114_514的基岩版玩家也进入服务器是否也会自动登录
> 
> 注册可以试着弄个GUI。你说的这个情况理论上不会出现，因为这两个玩家的UUID不一样，自动登录了也不会使用一样的数据，这点是可以保证的。但是有可能会因为ID相同被踢出（？）

还有件事，我试了一下你的注册gui发送，挺多方法都是弃用+移除，floodgate-api版本2.2.0-SNAPSHOT

**Comment by DongShaoNB** [comment]
> > > > > authme默认在玩家未注册的情况下会拦截所有交互行为，所有事件都要过一遍listenerService，或许可以参考下这个：https://github.com/HaHaWTH/AuthMeReReloaded/blob/master/src/main/java/fr/xephi/authme/listener/ListenerService.java#L87
> > > > > authme的配置文件中也提供了InventoryWhitelist的配置项，只要知道基岩版gui的窗口名的话或许也可以(? 貌似都需要在authme上动刀子
> > > > 
> > > > 
> > > > 但是基岩版直接跳过登录不是更方便吗🤔
> > > 
> > > 
> > > 感觉注册也需要一个gui，毕竟注册这东西没法跳过🧐
> > > 跳过登录可能有潜在的绕过问题(未测试)：
> > > 如：玩家114 514通过Geyser+floodgate进入服务器，floodgate会自动将空格换为下划线，此时如果有一个114_514的基岩版玩家也进入服务器是否也会自动登录
> > 
> > 注册可以试着弄个GUI。你说的这个情况理论上不会出现，因为这两个玩家的UUID不一样，自动登录了也不会使用一样的数据，这点是可以保证的。但是有可能会因为ID相同被踢出（？）
> 
> 还有件事，我试了一下你的注册gui发送，挺多方法都是弃用+移除，floodgate-api版本2.2.0-SNAPSHOT

这个不影响使用 后续会更换使用新的API
