### ISSUE TITLE
[FEATURE] 基岩版GUI菜单

### ISSUE THREAD

**Issue by MengYuanZhi** [DongShaoNB/BedrockPlayerSupport#70]
**功能**
1.能够实现基岩版的菜单
2.兼容大部分上的菜单（能用一物品区分java/基岩菜单）
3.可视化菜单编辑
**补充**
补充其他信息
第三个样式可以参考https://github.com/XCLHove/LiteLoaderBDSPlugins-XMenu/
希望可以采用

**Comment by DongShaoNB** [comment]
意思是能创建自定义的表单？

**Comment by MengYuanZhi** [comment]
对的

**Comment by DongShaoNB** [comment]
我们没有计划做这个，因为已经有现成的插件
https://github.com/kejonaMC/CrossplatForms

**Comment by MengYuanZhi** [comment]
好的了解
