### ISSUE TITLE
[FEATURE] Support EssentialsX kit munu and other feature

### ISSUE THREAD

**Issue by VincentX0905** [DongShaoNB/BedrockPlayerSupport#72]
**描述功能**
1. Support EssentialsX kit menu
https://jd-v2.essentialsx.net/com/earth2me/essentials/kits
https://jd-v2.essentialsx.net/com/earth2me/essentials/kit
2. Java menu
This plugin seems to integrate many functions into one menu.
I hope it will not only support Bedrock version
I hope it can also be supported in Java (Java does not have forms, only chest menu is used)
3. Reload can reload the language configuration

Expect to hear from you~

**补充**
None

**Comment by DongShaoNB** [comment]
1. I will support EssX kit menu if i can
2. We can't offer form for Java version
3. Actually, it can reload lang config

Thanks for your suggestions

**Comment by DongShaoNB** [comment]
Please try it, Download here https://github.com/DongShaoNB/BedrockPlayerSupport/actions/runs/10432599945
