### ISSUE TITLE
[BUG] Home list with HuskHomes

### ISSUE THREAD

**Issue by pintoso** [DongShaoNB/BedrockPlayerSupport#86]
**BUG Description**
Using HuskHomes, the home names in the home list appear as `nickname.homename`.  
So, if your name is `notch` and you set a home with the name `test`, it will appear in the home list as `notch.test`.  
I understand that this is because the HuskHomes command is targeted to that specific player's home, but in the home list, it's not very user-friendly.  
I recommend changing the logic of this function so that visually it only shows the home name, and only on the backend does it add the `nickname.`.

**Steps to Reproduce**
How to reproduce this bug:
1. Add HuskHomes and configure it.
2. Set a home.
3. Open the home list.

**Screenshots**
![image](https://github.com/user-attachments/assets/7e66c394-fd0e-4333-8197-f637c291cf13)

**Environment**
- Server and version: `Purpur 1.21.1`
- Plugin version: `2.0.2`
- Other additions: `HuskHomes-Paper-4.7.1`

**Comment by DongShaoNB** [comment]
Yes, this issue has actually been fixed, but because the developer is busy with personal matters, no official version has been released, you can get it fixed in the development version

https://github.com/DongShaoNB/BedrockPlayerSupport/actions/runs/11009766830
